"""
Compliance Evaluation Scorer with LLM
Scores question-answer pairs using semantic evaluation (1-10 scale)

Pass 1: Evaluate AI answer against expected answer ("check")
Pass 2: If score <= RECHECK_THRESHOLD, re-evaluate using full source file from KB dir
"""
import argparse
import json
import os
import re
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List, Optional

from config import (
    DEFAULT_PROVIDER,
    OLLAMA_TIMEOUT,
    PROVIDER_CONFIGS,
    PROVIDER_KIND_MAP,
)
from providers.base import LLMProvider
from providers.factory import create_provider, normalize_provider_name

# Constants
DEFAULT_TEMPERATURE = 0.0
DEFAULT_SLEEP = 0.3
ENV_FILE = ".env"
RECHECK_THRESHOLD = 7  # Re-evaluate with full file if score is in range [5, threshold]


# ─────────────────────────────────────────────
# SYSTEM PROMPTS
# ─────────────────────────────────────────────

SYSTEM_PROMPT = """
You are a Professional Quality Assurance Evaluator for Corporate Compliance AI Systems.

### GOAL:
Evaluate whether the AI Answer matches the Expected Answer (ground truth) in meaning.

### INPUTS:
- Question: the user-facing test question
- Requirement Context: optional PCI DSS requirement or background information
- Main Content: the original testing procedure / audit intent
- Expected Answer: the semantic ground truth (field `check`)
- AI Answer: the candidate answer generated by the agent

### EVALUATION PHILOSOPHY:
- Focus on **semantic equivalence**, not exact wording.
- The AI Answer does NOT need to mention company names or proprietary internal terms from the Expected Answer.
- If the Expected Answer says a company maintains a formal approval process, an AI Answer like
  "There is a formal process to approve and test network connections and firewall changes" can still be highly correct.
- Penalize only when the AI Answer misses key compliance meaning, contradicts it, or adds specific unsupported facts.

### WHAT COUNTS AS A MATCH:
The AI Answer should capture the core compliance meaning of the Expected Answer, such as:
- a formal / documented process exists
- approval and/or testing is required
- the relevant scope is correct (for example network connections, firewall changes, router changes)

### SCORING RUBRIC:

#### ENTAILED (Strong semantic match)
- **10**: Meaning is fully aligned with the Expected Answer. No factual issues.
- **9**: Strong match with minor wording differences or harmless abstraction.
- **8**: Correct core idea, possibly more generic than Expected Answer, but still clearly aligned.
- **7**: Mostly correct, but slightly incomplete, vague, or wordy.

#### PARTIAL / BORDERLINE
- **6**: Core idea is partly right, but one important element is weakened, omitted, or replaced by something too generic.
- **5**: Borderline. Some overlap exists, but the answer is too vague to trust without additional evidence.

#### NOT SUPPORTED / INCORRECT
- **4**: Only a small portion matches the Expected Answer.
- **3**: Misinterprets a key detail.
- **2**: Contradicts the Expected Answer on core meaning.
- **1**: Completely wrong, fabricated, or unrelated.

### MANDATORY RULES:
1. Ignore company names and proprietary labels in the Expected Answer unless they change the meaning.
2. Do not require exact string overlap.
3. Never forgive wrong numbers, wrong names, wrong dates, or explicit contradictions.
4. If the AI Answer adds specific extra facts that are NOT present in the Expected Answer, do not heavily penalize in Pass 1 unless they are clearly suspicious.
   Borderline cases (scores 5-7) will be verified in Pass 2 using the full source file.
5. If the AI Answer is empty, score 1.

### EVALUATION ORDER:
1. First read Requirement Context and Main Content to identify the compliance scope and audit intent.
2. Then read Expected Answer as the semantic ground truth summary.
3. Then compare AI Answer against that intent and expected meaning.
4. Do not judge based only on wording overlap between AI Answer and Expected Answer.
5. If AI Answer matches the audit intent in Main Content and preserves the core meaning of Expected Answer, score it accordingly.

### IMPORTANT NOTE:
Requirement Context and Main Content must be used first to understand what is actually being checked.
Expected Answer is the semantic ground truth, but it may be shorter or more specific than the full audit intent.

### OUTPUT FORMAT (JSON ONLY):
{
  "label": "ENTAILED | PARTIAL | NOT_MATCH | CONTRADICTED",
  "score": number (1-10),
  "confidence": number (0-1),
  "reason": "Giải thích ngắn gọn bằng tiếng Việt. Tập trung vào việc Answer có khớp ý với Expected Answer hay không."
}
"""

SYSTEM_PROMPT_CLAIM_EXTRACTOR = """
You are a precise fact extraction assistant for compliance evaluation.

### GOAL:
Given a Question, Expected Answer, and AI Answer, extract ONLY the specific claims in the AI Answer
that go BEYOND what the Expected Answer already provides.

### RULES:
1. A "claim" is any specific factual statement: a number, a name, a date, a status, a field value, a scope item, a step, a rule, a URL, or a role.
2. SKIP claims that are:
   - Already stated in the Expected Answer (even if rephrased slightly)
   - Clearly inherited from the Question
   - Generic professional language ("đảm bảo tuân thủ", "theo quy trình", "giúp minh bạch")
   - File name citations or metadata
3. INCLUDE claims that are:
   - Specific field values, system names, dates, numbers, approvals, scopes, records, or steps that are NOT in the Expected Answer
   - Strongly specific operational details not present in the Expected Answer
4. If the AI Answer only paraphrases the Expected Answer more generically, return no extra claims.

### OUTPUT FORMAT (JSON ONLY):
{
  "extra_claims": [
    "claim 1",
    "claim 2"
  ],
  "claim_count": number
}

If there are no extra claims, return: {"extra_claims": [], "claim_count": 0}
"""

SYSTEM_PROMPT_PASS2 = """
You are a Professional Quality Assurance Evaluator for Corporate Compliance AI Systems.

### GOAL:
Re-evaluate a borderline AI Answer using the FULL SOURCE FILE.
Your final judgment must consider BOTH:
1. Whether the AI Answer is supported by the Full Source File, and
2. Whether the AI Answer still matches the Expected Answer in meaning.

### CONTEXT:
- Pass 1 compared AI Answer vs Expected Answer and gave a borderline score (5-7).
- A Claim Extractor identified extra claims in the AI Answer that were not explicit in the Expected Answer.
- Your job is to verify those extra claims against the Full Source File.
- Pass 2 is primarily intended to RAISE confidence for borderline answers that may be correct but more detailed.
- Your score will only be used if it is HIGHER than Pass 1.

### VERIFICATION PROCESS:
For each extra claim:
  ✅ SUPPORTED     — found verbatim or clearly implied in the full file
  ❌ CONTRADICTED  — the file says something explicitly different
  ❓ NOT_FOUND     — cannot be found in the file

### HOW TO SCORE:
1. First, judge whether the AI Answer matches the Expected Answer semantically.
   - If it clearly contradicts or misses the core meaning of the Expected Answer, do NOT raise the score.
2. Then verify the extra claims against the Full Source File.
3. Use this guidance:
   - Strong semantic match + all/most extra claims SUPPORTED → 8-10
   - Strong semantic match + extra claims mostly NOT_FOUND but harmless/non-specific → 7-8
   - Strong semantic match + extra claims include unsupported specific details → at most 7
   - Any CONTRADICTED extra claim → at most 6
   - Semantic mismatch with Expected Answer → keep score low, even if some file evidence exists

### IMPORTANT RULES:
1. NOT_FOUND is not the same as wrong. It only limits how much confidence you can gain.
2. CONTRADICTED is wrong.
3. Do NOT reward extra facts if they drift away from the Expected Answer's core meaning.
4. Ignore company names / proprietary names if the answer preserves the same compliance meaning.
5. If extra_claims is empty, you may still use the Full Source File to determine whether the AI Answer is a faithful, acceptable paraphrase of the Expected Answer.

### OUTPUT FORMAT (JSON ONLY):
{
  "label": "ENTAILED | PARTIAL | NOT_MATCH | CONTRADICTED",
  "score": number (1-10),
  "confidence": number (0-1),
  "reason": "Giải thích ngắn gọn bằng tiếng Việt. Nêu rõ AI Answer có khớp Expected Answer không và các extra claim có được file hỗ trợ hay không.",
  "verified_claims": [
    {"claim": "...", "status": "SUPPORTED | NOT_FOUND | CONTRADICTED", "note": "lý do ngắn gọn"}
  ]
}
"""


# ─────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────

@dataclass(frozen=True)
class EvaluatorConfig:
    """Runtime configuration for the evaluator."""
    input_path: str
    output_path: str
    provider: str
    temperature: float
    sleep_time: float
    ollama_model: str
    ollama_url: str
    base_url: Optional[str] = None
    model: Optional[str] = None
    kb_dir: Optional[str] = None
    recheck_threshold: int = RECHECK_THRESHOLD
    pass2_enabled: bool = True
    qa_file: Optional[str] = None
    pci_file: Optional[str] = None
    context_field: str = "qa/visa/output.json"
    expected_field: str = "customer_only"
    main_field: str = "testing_procedures"
    id_field: str = "id"


# ─────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────

def get_expected_answer(item: Dict) -> str:
    return str(item.get("check") or item.get("expected") or "").strip()


def get_ai_answer(item: Dict) -> str:
    return str(item.get("answer") or "").strip()


def get_requirement_context(item: Dict) -> str:
    return str(item.get("context") or item.get("pci_dss_requirements") or "").strip()


def get_main_content(item: Dict) -> str:
    return str(item.get("main_content") or item.get("testing_procedures") or item.get("chunk") or "").strip()


# ─────────────────────────────────────────────
# KB FILE LOOKUP
# ─────────────────────────────────────────────

def find_kb_file(file_name: str, kb_dir: str) -> Optional[Path]:
    """
    Locate a KB file on disk.

    The 'file' field in JSON is like: 20260206_PRT_DanhSach_Danh_sach_MC_final_10.md
    The actual file on disk may have a random hash suffix added:
        20260206_PRT_DanhSach_Danh_sach_MC_final_10__76vsy07.md
    """
    kb_path = Path(kb_dir)
    if not kb_path.is_dir():
        return None

    exact = kb_path / file_name
    if exact.exists():
        return exact

    stem = Path(file_name).stem
    for candidate in kb_path.glob("*.md"):
        if candidate.stem.startswith(stem) or stem.startswith(candidate.stem):
            return candidate

    for candidate in kb_path.glob("*.md"):
        if stem in candidate.stem or candidate.stem in stem:
            return candidate

    return None


def read_kb_file(file_name: str, kb_dir: str, max_chars: int = 80_000) -> Optional[str]:
    """Read full content of a KB source file. Truncates at max_chars to stay within LLM limits."""
    path = find_kb_file(file_name, kb_dir)
    if path is None:
        return None
    content = path.read_text(encoding="utf-8")
    if len(content) > max_chars:
        content = content[:max_chars] + f"\n\n[... FILE TRUNCATED AT {max_chars} CHARS ...]"
    return content


# ─────────────────────────────────────────────
# PROMPT BUILDERS
# ─────────────────────────────────────────────

def build_user_prompt(item: Dict) -> str:
    """Build Pass 1 evaluation prompt from compliance test item."""
    return f"""
Question:
{item.get("question", "")}

Requirement Context:
{get_requirement_context(item)}

Main Content:
{get_main_content(item)}

Expected Answer:
{get_expected_answer(item)}

AI Answer:
{get_ai_answer(item)}
""".strip()


def build_user_prompt_claim_extractor(item: Dict) -> str:
    """Build prompt for Claim Extractor — identifies extra claims beyond the expected answer."""
    return f"""
Question:
{item.get("question", "")}

Expected Answer:
{get_expected_answer(item)}

AI Answer:
{get_ai_answer(item)}
""".strip()


def build_user_prompt_pass2(
    item: Dict,
    file_content: str,
    extra_claims: List[str],
) -> str:
    """Build Pass 2 verification prompt — verifies each extra claim against the full file."""
    claims_block = "\n".join(f"  - {c}" for c in extra_claims) if extra_claims else "  (none identified)"
    return f"""
Question:
{item.get("question", "")}

Requirement Context:
{get_requirement_context(item)}

Main Content:
{get_main_content(item)}

Expected Answer:
{get_expected_answer(item)}

Extra Claims to Verify:
{claims_block}

Full Source File Content:
{file_content}

AI Answer:
{get_ai_answer(item)}
""".strip()


def build_messages(provider_name: str, prompt: str, system: str = SYSTEM_PROMPT) -> List[Dict[str, str]]:
    """Build message array based on provider type."""
    if provider_name == "anthropic":
        return [{"role": "user", "content": f"{system}\n\n{prompt}"}]
    return [
        {"role": "system", "content": system},
        {"role": "user", "content": prompt},
    ]


# ─────────────────────────────────────────────
# LLM CALLS
# ─────────────────────────────────────────────

def parse_llm_response(response_text: str) -> Dict:
    """Extract and parse JSON from LLM response. Handles truncated responses gracefully."""
    if not response_text:
        raise ValueError("Empty response from LLM")

    text = re.sub(r'^```(?:json)?\s*', '', response_text.strip(), flags=re.IGNORECASE)
    text = re.sub(r'\s*```$', '', text.strip())

    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass

    json_match = re.search(r'\{.*\}', text, re.DOTALL)
    if json_match:
        try:
            return json.loads(json_match.group(0))
        except json.JSONDecodeError:
            pass

    salvaged = _salvage_truncated_json(text)
    if salvaged:
        return salvaged

    raise ValueError(f"Cannot parse JSON from response: {text[:200]}")


def _salvage_truncated_json(text: str) -> Optional[Dict]:
    start = text.find('{')
    if start == -1:
        return None

    fragment = text[start:]
    depth_obj = 0
    depth_arr = 0
    in_string = False
    i = 0
    while i < len(fragment):
        c = fragment[i]
        if c == '\\' and in_string:
            i += 2
            continue
        if c == '"':
            in_string = not in_string
        elif not in_string:
            if c == '{':
                depth_obj += 1
            elif c == '}':
                depth_obj -= 1
            elif c == '[':
                depth_arr += 1
            elif c == ']':
                depth_arr -= 1
        i += 1

    suffix = ''
    if in_string:
        suffix += '"'
    suffix += ']' * depth_arr
    trimmed = (fragment + suffix).rstrip()
    if trimmed.endswith(','):
        trimmed = trimmed[:-1]
    suffix_final = '}}' if depth_obj > 1 else ('}' if depth_obj >= 1 else '')
    candidate = trimmed + suffix_final

    try:
        result = json.loads(candidate)
        result['_truncated'] = True
        return result
    except json.JSONDecodeError:
        return None


def call_llm(
    provider: LLMProvider,
    provider_name: str,
    item: Dict,
    temperature: float,
    system: str = SYSTEM_PROMPT,
    prompt_override: Optional[str] = None,
    max_tokens: int = 2000,
) -> Dict:
    """Call LLM for semantic evaluation. Returns parsed JSON dict."""
    prompt = prompt_override if prompt_override is not None else build_user_prompt(item)
    messages = build_messages(provider_name, prompt, system=system)

    response_text = provider.chat(
        messages,
        temperature=temperature,
        max_tokens=max_tokens,
    )

    try:
        return parse_llm_response(response_text)
    except Exception as e:
        raise ValueError(f"Invalid JSON response: {e}\nRaw: {response_text[:300]}")


def extract_claims(
    provider: LLMProvider,
    provider_name: str,
    item: Dict,
    temperature: float,
) -> List[str]:
    """
    Identify specific factual claims in the AI answer that go BEYOND what the expected answer provides.
    Returns a list of claim strings, or [] on failure.
    """
    prompt = build_user_prompt_claim_extractor(item)
    messages = build_messages(provider_name, prompt, system=SYSTEM_PROMPT_CLAIM_EXTRACTOR)

    response_text = provider.chat(
        messages,
        temperature=temperature,
        max_tokens=1000,
    )

    try:
        result = parse_llm_response(response_text)
        claims = result.get("extra_claims", [])
        return [str(c) for c in claims if c]
    except Exception:
        return []


# ─────────────────────────────────────────────
# SCORE MAPPING
# ─────────────────────────────────────────────

def map_score_to_evaluate(score: int) -> str:
    """Map numeric score to evaluation category."""
    if score >= 6:
        return "correct"
    elif score == 5:
        return "unclear"
    else:
        return "incorrect"


# ─────────────────────────────────────────────
# JOIN MODE (QA + PCI BY ID)
# ─────────────────────────────────────────────

def build_joined_items(config: EvaluatorConfig) -> List[Dict]:
    """Join QA output with PCI filtered data by id."""
    if not config.qa_file or not config.pci_file:
        raise ValueError("qa_file and pci_file are required for join mode")

    qa_path = Path(config.qa_file)
    pci_path = Path(config.pci_file)
    if not qa_path.exists():
        raise FileNotFoundError(f"QA file not found: {qa_path}")
    if not pci_path.exists():
        raise FileNotFoundError(f"PCI file not found: {pci_path}")

    qa_data = json.loads(qa_path.read_text(encoding="utf-8"))
    pci_data = json.loads(pci_path.read_text(encoding="utf-8"))

    pci_by_id = {}
    for row in pci_data:
        pid = str(row.get(config.id_field, "")).strip()
        if pid:
            pci_by_id[pid] = row

    joined: List[Dict] = []
    missing = 0
    for row in qa_data:
        qid = str(row.get(config.id_field, "")).strip()
        if not qid:
            missing += 1
            continue
        pci_row = pci_by_id.get(qid)
        if not pci_row:
            missing += 1
            continue

        context_val = pci_row.get(config.context_field, "")
        if (not str(context_val).strip()) and config.context_field != "pci_dss_requirements":
            # Fallback for PCI filtered files that store context in pci_dss_requirements
            context_val = pci_row.get("pci_dss_requirements", "")

        joined.append({
            "id": qid,
            "question": row.get("question", ""),
            "answer": row.get("answer", ""),
            "context": context_val,
            "main_content": pci_row.get(config.main_field, ""),
            "check": pci_row.get(config.expected_field, ""),
            "source": row.get("source", []),
        })

    if missing > 0:
        print(f"⚠ join mode: skipped {missing} item(s) due to missing id or PCI match")

    return joined

# ─────────────────────────────────────────────
# PROCESS ITEM (3-step: Pass1 → Claim Extract → Pass2)
# ─────────────────────────────────────────────

def process_item(
    provider: LLMProvider,
    provider_name: str,
    config: EvaluatorConfig,
    item: Dict,
    idx: int,
) -> None:
    """
    Evaluate a single compliance test item.

    Step 1 — Pass 1   : evaluate AI Answer vs Expected Answer
    Step 2 — Extract  : if 5 <= score <= threshold, extract extra claims from AI Answer beyond Expected Answer
    Step 3 — Pass 2   : verify each extra claim against the full KB source file and re-evaluate

    Items with score ≤ 4 are not rechecked because the answer is already clearly incorrect.
    """
    try:
        nli = call_llm(provider, provider_name, item, config.temperature)
        score = int(nli.get("score", 0) or 0)
        label = nli.get("label", "UNKNOWN")
        confidence = float(nli.get("confidence", 0) or 0)

        item["pass1_score"] = score
        item["pass1_check"] = nli.get("reason", "")
        item["rechecked"] = False

        print(f"[{idx}] Pass1 → {label} (score: {score}, conf: {confidence:.2f})", end="")

        should_recheck = (
            config.pass2_enabled
            and (5 <= score <= config.recheck_threshold)
            and bool(config.kb_dir)
        )

        if not should_recheck:
            if score <= 4 and config.kb_dir:
                print(f"  →  pass2 skipped (clearly incorrect, score={score})")
            else:
                print()
        else:
            file_name = str(item.get("file") or "").strip()
            if not file_name:
                print("  →  skipped (no file field)")
            else:
                file_content = read_kb_file(file_name, config.kb_dir)
                if not file_content:
                    print(f"  →  skipped (file not found: {file_name})")
                else:
                    extra_claims = extract_claims(provider, provider_name, item, config.temperature)

                    MAX_CLAIMS = 15
                    if len(extra_claims) > MAX_CLAIMS:
                        print(f"  →  {len(extra_claims)} extra claim(s) (capped to {MAX_CLAIMS})", end="")
                        extra_claims = extra_claims[:MAX_CLAIMS]
                    else:
                        print(f"  →  {len(extra_claims)} extra claim(s)", end="")

                    pass2_max_tokens = min(500 + len(extra_claims) * 150, 4000)
                    pass2_prompt = build_user_prompt_pass2(item, file_content, extra_claims)
                    nli2 = call_llm(
                        provider,
                        provider_name,
                        item,
                        config.temperature,
                        system=SYSTEM_PROMPT_PASS2,
                        prompt_override=pass2_prompt,
                        max_tokens=pass2_max_tokens,
                    )

                    if nli2.get("_truncated"):
                        print(" ⚠ truncated", end="")
                    score2 = int(nli2.get("score", 0) or 0)
                    label2 = nli2.get("label", "UNKNOWN")
                    conf2 = float(nli2.get("confidence", 0) or 0)

                    pass1_score = item["pass1_score"]
                    score2 = max(score2, pass1_score)
                    nli2["score"] = score2

                    print(f"  →  Pass2 → {label2} (score: {score2}, conf: {conf2:.2f})")

                    nli = nli2
                    score = score2
                    item["rechecked"] = True
                    item["extra_claims"] = extra_claims
                    item["pass2_score"] = score2
                    item["pass2_check"] = nli2.get("reason", "")
                    item["pass2_verified_claims"] = nli2.get("verified_claims", [])

        item["evaluate"] = map_score_to_evaluate(score)
        item["score"] = score
        item["eval_reason"] = nli.get("reason", "")

    except Exception as e:
        item["evaluate"] = "error"
        item["score"] = 0
        item["eval_reason"] = str(e)
        item["rechecked"] = False
        print(f"\n[{idx}] ERROR → {e}")


# ─────────────────────────────────────────────
# EVALUATION LOOP
# ─────────────────────────────────────────────

def run_evaluation(config: EvaluatorConfig, provider: LLMProvider, provider_name: str) -> None:
    """Main evaluation loop."""
    input_path = Path(config.input_path)
    output_path = Path(config.output_path) if config.output_path else input_path.with_name(f"{input_path.stem}_semantic_scored.json")

    if config.qa_file and config.pci_file:
        data = build_joined_items(config)
        if not config.output_path:
            output_path = input_path.with_name(f"{input_path.stem}_joined_scored.json")
    else:
        data = json.loads(input_path.read_text(encoding="utf-8"))
    total = len(data)

    print(f"Loaded   : {input_path.name}")
    print(f"Total    : {total}")
    print(f"Provider : {provider_name.upper()}")
    if config.base_url:
        print(f"URL      : {config.base_url}")
    if config.model:
        print(f"Model    : {config.model}")
    if config.qa_file and config.pci_file:
        print(f"Join     : {config.qa_file}  +  {config.pci_file}")
        print(f"Fields   : context='{config.context_field}', main='{config.main_field}', expected='{config.expected_field}', id='{config.id_field}'")
    if config.kb_dir:
        if config.pass2_enabled:
            print(f"KB dir   : {config.kb_dir}  (2-pass enabled for score ≤ {config.recheck_threshold})")
        else:
            print(f"KB dir   : {config.kb_dir}  (2-pass disabled via --pass2 off)")
    else:
        print("KB dir   : not set  (1-pass only)")
    print()

    for idx, item in enumerate(data, start=1):
        process_item(provider, provider_name, config, item, idx)
        if idx < total:
            time.sleep(config.sleep_time)

    output_path.write_text(
        json.dumps(data, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )

    print(f"\n{'='*80}")
    print_statistics(data)
    print(f"\n✅ Saved to: {output_path}")


# ─────────────────────────────────────────────
# STATISTICS
# ─────────────────────────────────────────────

def print_statistics(data: List[Dict]) -> None:
    """Print evaluation statistics."""
    evaluate_counts = {"correct": 0, "incorrect": 0, "unclear": 0, "error": 0}
    score_sum = 0
    score_count = 0
    score_dist = {i: 0 for i in range(1, 11)}

    rechecked_total = 0
    rechecked_improved = 0

    for item in data:
        evaluate = item.get("evaluate", "error")
        evaluate_counts[evaluate] = evaluate_counts.get(evaluate, 0) + 1

        score = item.get("score", 0)
        if score > 0:
            score_sum += score
            score_count += 1
            if 1 <= score <= 10:
                score_dist[score] += 1

        if item.get("rechecked"):
            rechecked_total += 1
            p1 = item.get("pass1_score", 0)
            p2 = item.get("pass2_score", 0)
            if p2 > p1:
                rechecked_improved += 1

    total = len(data)
    avg_score = score_sum / score_count if score_count > 0 else 0

    print("Evaluation Summary:")
    print(f"   Total      : {total}")
    print(f"   Correct    : {evaluate_counts['correct']:3d} ({evaluate_counts['correct']/total*100:5.1f}%) [score ≥ 6]")
    print(f"   Unclear    : {evaluate_counts['unclear']:3d} ({evaluate_counts['unclear']/total*100:5.1f}%) [score = 5]")
    print(f"   Incorrect  : {evaluate_counts['incorrect']:3d} ({evaluate_counts['incorrect']/total*100:5.1f}%) [score ≤ 4]")
    print(f"   Error      : {evaluate_counts['error']:3d} ({evaluate_counts['error']/total*100:5.1f}%)")
    print(f"   Avg Score  : {avg_score:.2f}/10")

    if rechecked_total > 0:
        print("\n2-Pass Stats:")
        print(f"   Rechecked        : {rechecked_total}")
        print(f"   Improved         : {rechecked_improved} ({rechecked_improved/rechecked_total*100:.1f}% of rechecked)")

        total_claims = 0
        supported = 0
        not_found = 0
        contradicted = 0
        for item in data:
            for vc in item.get("pass2_verified_claims", []):
                total_claims += 1
                status = vc.get("status", "")
                if status == "SUPPORTED":
                    supported += 1
                elif status == "CONTRADICTED":
                    contradicted += 1
                else:
                    not_found += 1

        if total_claims > 0:
            print(f"\n   Claim Verification ({total_claims} total extra claims):")
            print(f"   ✅ Supported    : {supported} ({supported/total_claims*100:.1f}%)")
            print(f"   ❓ Not found    : {not_found} ({not_found/total_claims*100:.1f}%)")
            print(f"   ❌ Contradicted : {contradicted} ({contradicted/total_claims*100:.1f}%)")

    print("\nScore Distribution:")
    for score in range(10, 0, -1):
        count = score_dist[score]
        if count > 0:
            bar = "█" * int(count / total * 50)
            print(f"   {score:2d}: {count:3d} {bar}")


# ─────────────────────────────────────────────
# ENV / ARG PARSING
# ─────────────────────────────────────────────

def load_env_file(env_path: str = ENV_FILE) -> None:
    """Load key=value pairs from a .env file into the process environment."""
    path = Path(env_path)
    if not path.exists():
        return
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        key = key.strip()
        value = value.strip().strip('"').strip("'")
        if key and key not in os.environ:
            os.environ[key] = value


def resolve_api_key(provider_name: str, cli_key: Optional[str]) -> Optional[str]:
    """Resolve API key from CLI or environment."""
    if cli_key:
        return cli_key
    return os.getenv(f"{provider_name.upper()}_API_KEY")


def build_arg_parser() -> argparse.ArgumentParser:
    provider_choices = sorted(PROVIDER_CONFIGS.keys()) + ["ollama"]

    parser = argparse.ArgumentParser(
        description="Compliance Evaluation Scorer - Semantic evaluation with 1-10 scale (2-pass support)",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # 1-pass
  python evaluate_json_rewritten.py --input qa_data.json --api-key YOUR_KEY

  # 2-pass with KB directory
  python evaluate_json_rewritten.py --input qa_data.json --api-key YOUR_KEY --kb-dir ./kb_files/

  # 2-pass with custom threshold
  python evaluate_json_rewritten.py --input qa_data.json --api-key YOUR_KEY --kb-dir ./kb_files/ --recheck-threshold 7

Input JSON fields supported:
  - question
  - check (or expected)
  - answer
  - context (optional)
  - main_content (optional)
  - file (optional, required for pass 2)

Scoring:
  Score ≥ 6: PASS
  Score = 5: BORDERLINE
  Score ≤ 4: FAIL

2-Pass Logic:
  Step 1 — Pass 1  : compare AI Answer vs Expected Answer
  Step 2 — Extract : find extra claims in AI Answer beyond Expected Answer
  Step 3 — Pass 2  : verify those claims against full KB source file and re-evaluate

  score ≤ 4 (incorrect) → skip pass 2
  score 5-7 (borderline) → run claim extract + pass 2
  score ≥ 8 (good)       → skip pass 2
        """,
    )
    parser.add_argument("--input", help="Input JSON file with evaluation items")
    parser.add_argument("--output", help="Output JSON file path (overrides default)")
    parser.add_argument(
        "--provider",
        choices=provider_choices,
        default=DEFAULT_PROVIDER,
        help=f"LLM provider (default: {DEFAULT_PROVIDER})",
    )
    parser.add_argument("--model", help="Model name to use (overrides default for provider)")
    parser.add_argument("--api-key", help="LLM API key (or set {PROVIDER}_API_KEY env var)")
    parser.add_argument("--base-url", help="Custom base URL for OpenAI-compatible APIs")
    parser.add_argument("--ollama-model", default="qwen2.5:7b", help="Ollama model name (default: qwen2.5:7b)")
    parser.add_argument("--ollama-url", default="http://localhost:11434", help="Ollama base URL")
    parser.add_argument(
        "--temperature",
        type=float,
        default=DEFAULT_TEMPERATURE,
        help=f"Temperature for LLM (default: {DEFAULT_TEMPERATURE})",
    )
    parser.add_argument(
        "--sleep",
        type=float,
        default=DEFAULT_SLEEP,
        help=f"Sleep time between requests in seconds (default: {DEFAULT_SLEEP})",
    )
    parser.add_argument(
        "--kb-dir",
        default=None,
        help="Directory containing KB source .md files (enables 2-pass evaluation)",
    )
    parser.add_argument("--qa-file", help="QA output JSON (for join-by-id mode)")
    parser.add_argument("--pci-file", help="PCI filtered JSON (for join-by-id mode)")
    parser.add_argument(
        "--context-field",
        default="qa/visa/output.json",
        help="Field name in PCI file to use as Context (default: qa/visa/output.json)",
    )
    parser.add_argument(
        "--expected-field",
        default="customer_only",
        help="Field name in PCI file to use as Expected Answer (default: customer_only)",
    )
    parser.add_argument(
        "--main-field",
        default="testing_procedures",
        help="Field name in PCI file to use as Main Content (default: testing_procedures)",
    )
    parser.add_argument(
        "--id-field",
        default="id",
        help="ID field used to join QA and PCI files (default: id)",
    )
    parser.add_argument(
        "--recheck-threshold",
        type=int,
        default=RECHECK_THRESHOLD,
        help=f"Run Pass 2 if Pass 1 score is in range [5, threshold] (default: {RECHECK_THRESHOLD}). Score ≤ 4 always skipped.",
    )
    parser.add_argument(
        "--pass2",
        choices=["on", "off"],
        default="on",
        help="Enable or disable Pass 2 verification (default: on). Use --pass2 off to force 1-pass only.",
    )
    return parser


# ─────────────────────────────────────────────
# MAIN
# ─────────────────────────────────────────────

def main() -> None:
    parser = build_arg_parser()
    args = parser.parse_args()

    load_env_file()
    env_ollama_url = os.getenv("OLLAMA_URL")
    env_ollama_model = os.getenv("OLLAMA_MODEL")

    provider_name = normalize_provider_name(args.provider)

    if args.qa_file or args.pci_file:
        if not (args.qa_file and args.pci_file):
            print("❌ Join mode requires both --qa-file and --pci-file")
            return
        if not args.input:
            args.input = args.qa_file
    else:
        if not args.input:
            print("❌ --input is required unless using join mode (--qa-file + --pci-file)")
            return

    config = EvaluatorConfig(
        input_path=args.input,
        output_path=args.output or "",
        provider=provider_name,
        temperature=args.temperature,
        sleep_time=args.sleep,
        ollama_model=env_ollama_model or args.ollama_model,
        ollama_url=env_ollama_url or args.ollama_url,
        base_url=args.base_url,
        model=args.model,
        kb_dir=args.kb_dir,
        recheck_threshold=args.recheck_threshold,
        pass2_enabled=(args.pass2 == "on"),
        qa_file=args.qa_file,
        pci_file=args.pci_file,
        context_field=args.context_field,
        expected_field=args.expected_field,
        main_field=args.main_field,
        id_field=args.id_field,
    )

    api_key: Optional[str] = None
    provider_kind = PROVIDER_KIND_MAP.get(config.provider)
    if provider_kind == "api":
        api_key = resolve_api_key(config.provider, args.api_key)
        if not api_key:
            provider_env = f"{config.provider.upper()}_API_KEY"
            print("❌ API key required!")
            print("   Use: --api-key YOUR_KEY")
            print(f"   Or set env: export {provider_env}=YOUR_KEY")
            return

    try:
        provider = create_provider(
            provider_name=config.provider,
            api_key=api_key,
            ollama_url=config.ollama_url,
            ollama_model=config.ollama_model,
            ollama_timeout=OLLAMA_TIMEOUT,
            base_url=config.base_url,
            model=config.model,
        )
    except ValueError as exc:
        print(f"❌ {exc}")
        return

    run_evaluation(config, provider, provider_name)


if __name__ == "__main__":
    main()
